session_name: Zea Engine
suppress_history: false
windows:
  - layout: main-vertical
    panes:
      - yarn run build:watch
      - ${EDITOR} -S
  - panes:
      - shell_command:
          - git fetch
          - git status
