import { ParameterOwner } from '../ParameterOwner'

/**
 * The BaseTool provides an interface you can implement to define your own mouse, keyboard, and touch event handlers.
 *
 * A tool is a class that is delegated the handling of all user interaction events. The built-in {CameraManipulator}
 * class provides a default tool for moving the viewport camera.
 *
 * You can define your own custom tool, and replace the default CameraManipulator like so.
 * ```javascript
 *   const customManipulator = new MyCustomCameraManipulator()
 *   renderer.getViewport().setManipulator(customManipulator)
 * ```
 *
 * Each tool should provide handlers for the main types of events it will be responsible for handling.
 * These include mouse, keyboard, touch and VR events. Once a tool is installed on the viewport, the viewport
 * will start invoking the handler methods defined in the interface.
 * If the Tool handles an event, it should call stopPropagation on the event so the engine knows to stop the
 * propagation of the event to other classes.
 *
 * > Note: VR Events are ann emulation of mouse events, generated by the engine, allowing custom tools to be used to provide various VR interactions.
 *
 * **Events**
 * * **installChanged:** Triggered when the tool is installed or uninstalled.
 * * **activatedChanged:** Triggered when a tool is activated or deactivated.
 *
 * @extends ParameterOwner
 */
class BaseTool extends ParameterOwner {
  protected __activated: boolean = false
  /**
   * Creates an instance of BaseTool.
   */
  constructor() {
    super()
  }

  /**
   * Enables tools usage. This method is called by either the Viewport when a tool is removed, or the ToolManage if it is installed.
   */
  activateTool() {
    if (this.__activated) throw new Error('Tool already activate')
    this.__activated = true
    this.emit('activatedChanged', { activated: this.__activated })
  }

  /**
   * Disables tool usage. This method is called by either the Viewport when a tool is removed, or the ToolManage if it is installed.
   */
  deactivateTool() {
    this.__activated = false
    this.emit('activatedChanged', { activated: this.__activated })
  }

  // ///////////////////////////////////
  // Pointer events

  /**
   * Event fired when either the mouse button is pressed, or a touch start event occurs.
   *
   * @param event - The event param.
   */
  onPointerDown(event: MouseEvent) {
    // console.warn('Implement me')
  }

  /**
   * Event fired when either the mouse cursor is moved, or a touch point moves.
   *
   * @param event - The event param.
   */
  onPointerMove(event: MouseEvent) {
    // console.warn('Implement me')
  }

  /**
   * Event fired when either the mouse button is released, or a touch end event occurs.
   *
   * @param event - The event param.
   */
  onPointerUp(event: MouseEvent) {
    // console.warn('Implement me')
  }

  /**
   * Event fired when a pointing device button is double clicked.
   *
   * @param event - The event param.
   */
  onPointerDoublePress(event: MouseEvent) {
    // console.warn('Implement me')
  }

  /**
   * Event fired when a mouse pointer enters the viewport
   *
   * @param event - The event param.
   */
  onPointerEnter(event: MouseEvent) {
    // console.warn('Implement me')
  }

  /**
   * Event fired when a mouse pointer leaves the viewport
   *
   * @param event - The event param.
   */
  onPointerLeave(event: MouseEvent) {
    // console.warn('Implement me')
  }

  /**
   * Event fired when the user rotates the pointing device wheel.
   *
   * @param event - The event param.
   */
  onWheel(event: MouseEvent) {
    // console.warn('Implement me')
  }

  // ///////////////////////////////////
  // Keyboard events

  /**
   * Event fired when the user presses down a key on the keyboard.
   *
   * @param event - The event param.
   */
  onKeyDown(event: KeyboardEvent) {
    // console.warn('Implement me')
  }

  /**
   * Event fired when the user releases a key on the keyboard.
   *
   * @param event - The event param.
   */
  onKeyUp(event: KeyboardEvent) {
    // console.warn('Implement me')
  }

  // ///////////////////////////////////
  // Touch events

  /**
   * Event fired when one or more touch points have been disrupted in an implementation-specific manner.
   *
   * @param event - The event param.
   */
  onTouchCancel(event: TouchEvent) {
    // console.warn('Implement me')
  }
}

export default BaseTool
export { BaseTool }
